name: 'bookstore-microservice'
services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: bookstore-tunnel
    restart: unless-stopped
    command: tunnel run
    env_file:
      - ./docker-compose.env
    networks:
      - bookstore-network


  bookstore-rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: bookstore-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    networks:
      - bookstore-network
    deploy:
      resources:
        limits:
          memory: 500m


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: [ 'start-dev', '--import-realm' ,'--http-port=9191' ]
    container_name: keycloak
    hostname: keycloak
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm-config:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin1234
    ports:
      - "9191:9191"
    networks:
      - bookstore-network
    deploy:
      resources:
        limits:
          memory: 2gb

  redis:
    image: redis:7.2-alpine
    container_name: bookstore-redis
    ports:
      - "6379:6379"
    networks:
      - bookstore-network
    deploy:
      resources:
        limits:
          memory: 256m

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: bookstore-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - bookstore-network
    deploy:
      resources:
        limits:
          memory: 1gb

volumes:
  keycloak_data:
  es_data:

networks:
  bookstore-network:
    external: true
