spring.application.name=catalog
server.port=8081
server.shutdown=graceful

######## Actuator Configuration  #########
management.info.git.mode=full
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.application.name}
management.tracing.enabled=false
management.tracing.sampling.probability=1.0

###### Database Configuration ######
spring.datasource.url=${CATALOG_DB_URL:jdbc:postgresql://ep-curly-thunder-a1mscwgq-pooler.ap-southeast-1.aws.neon.tech/catalog_db?user=neondb_owner&password=npg_iHvlGejoBa38&sslmode=require&channelBinding=require}
spring.datasource.username=${CATALOG_DB_USERNAME:neondb_owner}
spring.datasource.password=${CATALOG_DB_PASSWORD:npg_iHvlGejoBa38}
spring.jpa.open-in-view=false

######## Catalog Service Configuration  #########
catalog.page-size=10

swagger.api-gateway-url=http://localhost:8989/catalog
