spring.application.name=payment-service
server.port=8084
server.shutdown=graceful
spring.mvc.problemdetails.enabled=true

spring.datasource.url=${PAYMENT_DB_URL}
spring.datasource.username=${PAYMENT_DB_USERNAME}
spring.datasource.password=${PAYMENT_DB_PASSWORD}
spring.jpa.open-in-view=false

spring.flyway.enabled=true

swagger.api-gateway-url=${SWAGGER_API_GATEWAY_URL:http://localhost:8989/payments}

management.info.git.mode=full
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.application.name}
management.tracing.enabled=false
management.tracing.sampling.probability=1.0

paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_CLIENT_SECRET}
paypal.mode=${PAYPAL_MODE:sandbox}