spring.application.name=payment-service
server.port=8084
server.shutdown=graceful
spring.mvc.problemdetails.enabled=true

spring.datasource.url=${PAYMENT_DB_URL:jdbc:postgresql://ep-curly-thunder-a1mscwgq-pooler.ap-southeast-1.aws.neon.tech/payment_db?user=neondb_owner&password=npg_iHvlGejoBa38&sslmode=require&channelBinding=require}
spring.datasource.username=${PAYMENT_DB_USERNAME:neondb_owner}
spring.datasource.password=${PAYMENT_DB_PASSWORD:npg_iHvlGejoBa38}
spring.jpa.open-in-view=false

spring.flyway.enabled=true

swagger.api-gateway-url=${SWAGGER_API_GATEWAY_URL:http://localhost:8989/payments}

management.info.git.mode=full
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.application.name}
management.tracing.enabled=false
management.tracing.sampling.probability=1.0

paypal.client.id=${PAYPAL_CLIENT_ID:AaCEYsloX1hfahlXFuu838n4MFyCcLQzJnAayq08b9eRhKOOghmQSftb2Ms2UQ2alM_PBpnSGUZgMSHe}
paypal.client.secret=${PAYPAL_CLIENT_SECRET:EBMAWZsLPvHFKqoKQwbF45ZHK5kWmTuTQUy2eNQMIBShOxPaGbGejrn4OKFd10OXsm5eRI5drW8GgmTD}
paypal.mode=${PAYPAL_MODE:sandbox}
bookstore.order-service-url=${ORDER_SERVICE_URL:http://localhost:8082}