server:
  port: 8085

spring:
  application:
    name: search-service
  elasticsearch:
    uris: ${ELASTICSEARCH_URL:http://localhost:9200}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
